### ISSUE TITLE
ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found

### ISSUE THREAD

**Issue by pat-s** [ArjenSchwarz/wercker-step-hugo-build#31]
Building works on localhost. When building on wercker, build is failing with `ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found`

`config.toml`: 
```toml
# Syntax Highlighting 
PygmentsCodeFences = true
pygmentsstyle = "emacs"
```

When building on wercker, build is failing with `ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found`

`Wercker.yml`:

```yml
box: golang:latest

build:
  steps:
    - add-to-known_hosts:
        hostname: github.com
        type: rsa
    - script:
        name: initialize and update git submodules
        code: |
            git submodule init
            git submodule update --remote --recursive
    - arjen/hugo-build:
        version: "HEAD"
        theme: academic
```
