### ISSUE TITLE
Build fails to cleanup

### ISSUE THREAD

**Issue by rac2030** [ArjenSchwarz/wercker-step-hugo-build#38]
I had a strange issue where the pygments highlighting was not anymore working.
Locally it was working but wercker did always deploy output with missing pygments output.

Solution was adding following to the wercker build:
```
    - script:
        name: cleanup
        code: rm -rf public/
# Build the HUGO page in public folder
    - arjen/hugo-build@1.14.1:
        version: "0.18.1"
        flags: --buildDrafts=false
```
After this it started working, does the public folder get cached on wercker?
If yes, would it make sense to add cleaning the public folder to it to have a clean room build?
