### ISSUE TITLE
Issue with wercker/default (HTTP 404)

### ISSUE THREAD

**Issue by herveDarritchon** [ArjenSchwarz/wercker-step-hugo-build#8]
This container seems to don't exist anymore ?

when I run wercker build with this wercker.yml

```
    box: wercker/default
    build:
      steps:
        - arjen/hugo-build:
            version: 0.14
            theme: hd-theme
            flags: --disableSitemap=true
```

I get an HTTP 404 error :
--> Executing pipeline
--> Running step: setup environment
ERROR Error during check access
ERROR --> Step failed: setup environment
GET https://registry.hub.docker.com/v1/repositories/wercker/default/images returned 404
ERROR GET https://registry.hub.docker.com/v1/repositories/wercker/default/images returned 404
